var fastFood = [
    "Wendy's",
    "Burger King",
    "McDonalds",
    "Taco Bell",
    "A&W",
    "Arby's",
    "Carl's Jr.",
    "Dairy Queen",
    "Five Guys",
    "KFC",
    "Popeyes Fried Chicken",
    "Quizno's",
    "Subway",
    "Firehouse Subs",
    "Zaxby's",
    "Chik-fil-a",
    "Mooyah",
    "In-N-Out Burger",
    "The Habit Burger Grill",
    "Pita Pit",
    "Sonic Drive-In",
    "Taco Time",
    "Del Taco"
]

var fastCasual = [
    "Costa Vida",
    "Cafe Rio",
    "El Pollo Loco",
    "Chipotle Mexian Grill",
    "Noodles & Co.",
    "Panda Express",
    "Cubby's Chicago Beef",
    "Spitz",
    "Pizzeria Limone",
    "Aubergine & Company",
    "Moochie's Meatballs & More!",
    "Even Stevens Sandwiches",
    "Sweeto Burrito",
    "Wild Zucchini Grill",
    "Malawis",
    "Waffle Love",
    "Bruges Waffles & Frites",
    "CHOM Burger"
]