var fastFood = [
    "Wendy's",
    "Burger King",
    "McDonalds",
    "Taco Bell",
    "A&W",
    "Arby's",
    "Carl's Jr.",
    "Dairy Queen",
    "Five Guys",
    "KFC",
    "Popeyes Fried Chicken",
    "Quizno's",
    "Subway",
    "Firehouse Subs",
    "Zaxby's",
    "Chik-fil-a",
    "Mooyah",
    "In-N-Out Burger",
    "The Habit Burger Grill",
    "Pita Pit",
    "Sonic Drive-In",
    "Taco Time",
    "Del Taco"
]

var fastCasual = [
    "Costa Vida",
    "Cafe Rio",
    "El Pollo Loco",
    "Chipotle Mexian Grill",
    "Noodles & Co.",
    "Panda Express",
    "Cubby's Chicago Beef",
    "Spitz",
    "Pizzeria Limone",
    "Aubergine & Company",
    "Moochie's Meatballs & More!",
    "Even Stevens Sandwiches",
    "Sweeto Burrito",
    "Wild Zucchini Grill",
    "Malawis",
    "Waffle Love",
    "Bruges Waffles & Frites",
    "CHOM Burger",
    "Cafe Zupas",
    "Bam Bams BBQ",
    "Culver's",
    "J Dawgs"
]

var sitDown = [
    "Tucanos Brazilian Grill",
    "Chili's Grill & Bar",
    "Black Bear Diner",
    "India Palace",
    "Kohinoor",
    "Black Sheep Cafe",
    "Station 22",
    "Bombay House",
    "The Copper Onion",
    "Blue Lemon",
    "Brick Oven",
    "Asado Argentinian Grill",
    "The Park Cafe",
    "The Pie Pizzeria",
    "Applebees",
    "Texas Roadhouse",
    "Outback Steakhouse",
    "The Cheesecake Factory",
    "Ruth's Chris Steak House",
    "Rodizio Grill",
    "Denny's",
    "Pago",
    "Carrabba's",
    "Pizzeria Seven Twelve",
    "Olive Garden",
    "The Old Spaghetti Factory",
    "Communal",
    "Shoots",
    "Spicy Thai",
    "Los Hermanos",
    "Mi Ranchito",
    "Lucy's Brazilian Kitchen"
]