var fastFood = [
    "Wendy's",
    "Burger King",
    "McDonalds",
    "Taco Bell",
    "A&W",
    "Arby's",
    "Carl's Jr.",
    "Dairy Queen",
    "Five Guys",
    "KFC",
    "Popeyes Fried Chicken",
    "Quizno's",
    "Subway",
    "Firehouse Subs",
    "Zaxby's",
    "Chik-fil-a",
    "Mooyah",
    "In-N-Out Burger",
    "The Habit Burger Grill",
    "El Pollo Loco",
    "Pita Pit",
    "Sonic Drive-In",
    "Taco Time",
    "Del Taco"
]